Fix empty sources

diff --git a/actions/claat-test/action.yml b/actions/claat-test/action.yml
--- a/actions/claat-test/action.yml
+++ b/actions/claat-test/action.yml
@@ -38,6 +38,13 @@ inputs:
 runs:
   using: "composite"
   steps:
+    - name: Check Runner OS
+      if: ${{ runner.os != 'Linux' }}
+      shell: bash
+      run: |
+        echo "::error title=⛔ error hint::Support Linux Only"
+        exit 1
+
     - name: Export Go bin to all steps
       id: go-env
       shell: bash
@@ -70,10 +77,12 @@ runs:
 
     - name: Get source(s)
       if: "${{ inputs.codelabs-json != '' }}"
+      id: data
       shell: bash
       run: |
         echo "::group::Get source(s)"
-        INPUT_SOURCE=$(cat ${{ inputs.codelabs-json }} | grep "source" | sed 's/.*": "\(.*\)"/\1/')
+        sources=$(cat ${{ inputs.codelabs-json }} | grep "source" | sed 's/.*": "\(.*\)"/\1/')
+        echo "sources=$sources" >> "$GITHUB_OUTPUT"
         echo "::endgroup::"
 
     - name: Command builder
@@ -89,12 +98,14 @@ runs:
 
     - name: Export codelab(s)
       shell: bash
+      env: 
+        SOURCES: ${{ if eq (length ${{ inputs.codelabs-json }}) 0 then inputs.source else steps.data.outputs.sources }}
       run: |
         echo "::group::Export codelab(s)"
         mkdir -p ${{ inputs.codelabs-path }}
-        echo -e "exporting\n$INPUT_SOURCE"
+        echo -e "exporting\n$SOURCES"
         IFS=$'\n'
-        for source in $INPUT_SOURCE; do
+        for source in $SOURCES; do
           command_default="${CLAAT_COMMAND} -o \"${{ inputs.codelabs-path }}/\" $source"
           if [[ "${{ inputs.format }}" == "all" ]]; then
             mkdir -p ${{ inputs.codelabs-path }}-md
@@ -119,3 +130,8 @@ runs:
         done
         echo "Missing ga4id in html format has been added."
         echo "::endgroup::"
+
+# Ref: https://haya14busa.github.io/github-action-brandings/
+branding:
+  icon: 'upload'
+  color: 'white'
