Remove claat-test

diff --git a/actions/claat/action.yml b/actions/claat/action.yml
--- a/actions/claat/action.yml
+++ b/actions/claat/action.yml
@@ -1,42 +1,68 @@
 name: "Claat export"
 
-description: "Export Google documents using claat as a codelab in html/md format"
+description: |
+  Exporting Google Sheets using claat as a codelab in HTML, Markdown, or offline format
 
 inputs:
   claat-version:
-    description: "claat version. By default 'latest' or 'vx.x.x'"
+    description: |
+      claat version.
+      Default is latest
     required: false
-    default: "latest"
-  document-id:
-    description: "Google document ID"
+    default: 'latest'
+  source:
+    description: |
+      Accepted File Formats: Google document ID Markdown file (.md)
+      If input \'codelabs-json\' is set, \'source\' will be ignored.
     required: true
   auth:
-    description: "Google OAuth2.0 token to access Google document"
-    required: true
+    description: |
+      A Google OAuth2.0 token is required to access Google documents.
+      (Except when exporting .md files to HTML.)
+      Default is ''
+    required: false
+    default: ''
   codelabs-path:
-    description: "Path where will you export the codelab"
+    description: |
+      Exported codelab(s) will be saved to your chosen path.
+      Default is codelabs
     required: false
-    default: "codelabs"
+    default: 'codelabs'
   gaid:
-    description: "Google Analytics ID"
+    description: |
+      Google Analytics ID
+      Default is UA-3295395-7
     required: false
-    default: "UA-3295395-7"
+    default: 'UA-3295395-7'
   ga4id:
-    description: "Google Analytics v4 ID"
+    description: |
+      Google Analytics v4 ID
+      Default is G-E0H6JSF2N3
     required: false
-    default: "G-E0H6JSF2N3"
+    default: 'G-E0H6JSF2N3'
   codelabs-json:
-    description: "Path of codelabs.json that contain a list of Google duments id "
+    description: |
+      The path to a JSON file containing a list of Google document IDs.
+      Default is ''
     required: false
-    default: ""
+    default: ''
   format:
-    description: "Codelab export format (html, md or all)."
+    description: |
+      Choose export format (html, md or all).
+      Default is html
     required: false
-    default: "html"
+    default: 'html'
 
 runs:
   using: "composite"
   steps:
+    - name: Check Runner OS
+      if: ${{ runner.os != 'Linux' }}
+      shell: bash
+      run: |
+        echo "::error title=⛔ error hint::Support Linux Only"
+        exit 1
+
     - name: Export Go bin to all steps
       id: go-env
       shell: bash
@@ -55,55 +81,58 @@ runs:
       with:
         path: |
           ${{ steps.go-env.outputs.go-bin-path }}/*
-        key: go-claat
+        key: go-claat-${{ inputs.claat-version }}
 
     - name: Setup claat (latest)
       if: steps.claat-cache.outputs.cache-hit != 'true'
       shell: bash
+      env:
+        VERSION: ${{ inputs.claat-version }}
       run: |
         echo "::group::Setup claat (latest)"
         mkdir -p $(go env GOPATH)/bin
-        go install github.com/googlecodelabs/tools/claat@${{ inputs.claat-version }}
+        go install github.com/googlecodelabs/tools/claat@$VERSION
         claat version
         echo "::endgroup::"
 
-    - name: Check codelabs directory
+    - name: Command builder
       shell: bash
+      env:
+        GAID: ${{ inputs.gaid }}
+        AUTH: ${{ inputs.auth }}
+        FORMAT: ${{ inputs.format }}
       run: |
-        echo "::group::Check codelabs directory"
-        if [ ! -d ${{ inputs.codelabs-path }} ]; then
-            mkdir ${{ inputs.codelabs-path }}
-            echo "${{ inputs.codelabs-path }} has been created."
-        fi
-        echo "::endgroup::"
-
-    - name: Create codelabs directory for md format
-      if: inputs.format == 'all'
-      shell: bash
-      run: |
-        echo "::group::Create codelabs directory for md format"
-        if [ ! -d ${{ inputs.codelabs-path }}-md ]; then
-            mkdir ${{ inputs.codelabs-path }}-md
-            echo "${{ inputs.codelabs-path }}-md has been created."
-        fi
+        echo "::group::Build command"
+        claat_command="claat export"
+        [[ -n "$GAID" ]] && claat_command+=" -ga \"$GAID\""  
+        [[ "$FORMAT" == "md" ]] && claat_command+=" -f \"$FORMAT\""
+        [[ -n "$AUTH" ]] && claat_command+=" -auth \"$AUTH\""
+        echo "CLAAT_COMMAND=$claat_command" >> $GITHUB_ENV 
         echo "::endgroup::"
 
     - name: Export codelab(s)
       shell: bash
+      env:
+        SOURCES: ${{ inputs.source }}
+        JSON_FILE: ${{ inputs.codelabs-json }}
+        OUTPOUT_PATH: ${{ inputs.codelabs-path }}
       run: |
         echo "::group::Export codelab(s)"
-        sources="${{ inputs.document-id }}"
-        if [[ -n "${{ inputs.codelabs-json }}" ]]; then
-          sources=$(cat codelabs.json | grep "source" | sed 's/.*": "\(.*\)"/\1/')
+        mkdir -p "$OUTPOUT_PATH"
+        if [[ "$JSON_FILE" != '' ]]; then
+          SOURCES=$(jq -r '.[].source' $JSON_FILE )
         fi
-        echo "exporting $sources"
+        echo -e "exporting\n$SOURCES"
         IFS=$'\n'
-        for source in $sources; do
+        for source in $SOURCES; do
+          command_default="${CLAAT_COMMAND} -o \"$OUTPOUT_PATH/\" $source"
           if [[ "${{ inputs.format }}" == "all" ]]; then
-            claat export -ga ${{ inputs.gaid }} -o "${{ inputs.codelabs-path }}/" -auth "${{ inputs.auth }}" "$source"
-            claat export -ga ${{ inputs.gaid }} -o "${{ inputs.codelabs-path }}-md/" -f "md" -auth "${{ inputs.auth }}" "$source"
+            mkdir -p "$OUTPOUT_PATH-md"
+            command_md="${CLAAT_COMMAND} -o \"$OUTPOUT_PATH-md/\" -f \"md\" $source"
+            eval "$command_default $@"
+            eval "$command_md $@"
           else
-            claat export -ga ${{ inputs.gaid }} -o "${{ inputs.codelabs-path }}/" -f "${{ inputs.format }}" -auth "${{ inputs.auth }}" "$source"
+            eval "$command_default $@"
           fi
         done
         echo "::endgroup::"
@@ -113,10 +142,17 @@ runs:
       shell: bash
       if: inputs.format != 'md'
       working-directory: ${{ inputs.codelabs-path }}
+      env:
+        GA4ID: ${{ inputs.ga4id }}
       run: |
         echo "::group::Fix missing ga4id"
         find . -type f -name "index.html" -print0 | while IFS= read -r -d '' file; do
-          sed -i 's/ga4id=""/ga4id="${{ inputs.ga4id }}"/g; s/codelab-ga4id=""/codelab-ga4id="${{ inputs.ga4id }}"/g' "$file"
+          sed -i 's/ga4id=""/ga4id="$GA4ID"/g; s/codelab-ga4id=""/codelab-ga4id="$GA4ID"/g' "$file"
         done
         echo "Missing ga4id in html format has been added."
         echo "::endgroup::"
+
+# Ref: https://haya14busa.github.io/github-action-brandings/
+branding:
+  icon: "upload"
+  color: "white"
